[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "gcc",
    "zlib",
    "libffi"
]

[phases.install]
cmds = [
    "python -m ensurepip --upgrade",
    "python -m pip install -r requirements.txt"
]

[phases.start]
cmd = "python manage.py migrate && gunicorn gestion_pedidos.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120"