[phases.setup]
nixPkgs = [
    "python311.full",  # Incluye pip y setuptools
    "gcc",
    "zlib",
    "libffi"
]

[phases.install]
cmds = [
    "python -m ensurepip --upgrade",  # Alternativa para instalar pip
    "python -m pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
cmd = "python manage.py migrate && gunicorn gestion_pedidos.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120"