[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",  # Asegura que pip esté instalado
    "gcc",
    "zlib",
    "libffi"
]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt"  # Usa 'python -m pip'
]

[phases.start]
cmd = "python manage.py migrate && gunicorn gestion_pedidos.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120"