# Generated by Django 5.1.7 on 2025-07-06 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(db_column='Categoria_ID', primary_key=True, serialize=False)),
                ('categoria_nombre', models.CharField(db_column='Categoria_nombre', max_length=100)),
                ('categoria_tipo', models.CharField(blank=True, db_column='Categoria_Tipo', max_length=100, null=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(db_column='Cliente_ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('email', models.CharField(db_column='Email', max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=255, null=True)),
                ('cedula', models.IntegerField(blank=True, db_column='Cedula', null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('envio_id', models.AutoField(db_column='Envio_ID', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='Tipo', max_length=50)),
                ('estado', models.CharField(db_column='Estado', max_length=50)),
            ],
            options={
                'db_table': 'envio',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('orden_id', models.AutoField(db_column='Orden_ID', primary_key=True, serialize=False)),
                ('fecha_orden', models.DateTimeField(db_column='Fecha_Orden')),
                ('cliente', models.ForeignKey(blank=True, db_column='Cliente_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.cliente')),
                ('envio', models.ForeignKey(blank=True, db_column='Envio_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.envio')),
            ],
            options={
                'db_table': 'orden',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('producto_id', models.AutoField(db_column='Producto_ID', primary_key=True, serialize=False)),
                ('producto_nombre', models.CharField(db_column='Producto_nombre', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, db_column='Categoria_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.categoria')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='OrdenDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.ForeignKey(db_column='Orden_ID', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.orden')),
                ('producto', models.ForeignKey(db_column='Producto_ID', on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='pedidos.productos')),
            ],
            options={
                'db_table': 'orden_detalle',
                'unique_together': {('orden', 'producto')},
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='productos',
            field=models.ManyToManyField(related_name='ordenes', through='pedidos.OrdenDetalle', to='pedidos.productos'),
        ),
    ]
