# Generated by Django 5.1.7 on 2025-04-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(db_column='Categoria_ID', primary_key=True, serialize=False)),
                ('categoria_nombre', models.CharField(db_column='Categoria_nombre', max_length=100)),
                ('categoria_tipo', models.CharField(blank=True, db_column='Categoria_Tipo', max_length=100, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(db_column='Cliente_ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('email', models.CharField(db_column='Email', max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=255, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('envio_id', models.AutoField(db_column='Envio_ID', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='Tipo', max_length=50)),
                ('estado', models.CharField(db_column='Estado', max_length=50)),
            ],
            options={
                'db_table': 'envio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('orden_id', models.AutoField(db_column='Orden_ID', primary_key=True, serialize=False)),
                ('fecha_orden', models.DateTimeField(db_column='Fecha_Orden')),
            ],
            options={
                'db_table': 'orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('producto_id', models.AutoField(db_column='Producto_ID', primary_key=True, serialize=False)),
                ('producto_nombre', models.CharField(db_column='Producto_nombre', max_length=100)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
    ]
