# Generated by Django 5.1.7 on 2025-08-04 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('producto', models.OneToOneField(db_column='Producto_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inventario', serialize=False, to='pedidos.productos')),
                ('cantidad_disponible', models.PositiveIntegerField(db_column='Cantidad_Disponible', default=0)),
                ('cantidad_minima', models.PositiveIntegerField(db_column='Cantidad_Minima', default=10)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, db_column='Ultima_Actualizacion')),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
    ]
