# Generated by Django 4.2.23 on 2025-08-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='producto_nombre',
            field=models.CharField(db_column='Producto_nombre', max_length=50),
        ),
    ]
