# Generated by Django 4.2.23 on 2025-08-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_productos_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='unidad',
            field=models.CharField(db_column='unidad', default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productos',
            name='producto_nombre',
            field=models.CharField(db_column='Producto_nombre', max_length=100),
        ),
    ]
