# Generated by Django 5.1.7 on 2025-05-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrden',
            fields=[
                ('item_id', models.AutoField(db_column='Item_ID', primary_key=True, serialize=False)),
                ('precio_historico', models.DecimalField(db_column='Precio_Historico', decimal_places=0, max_digits=10)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('subtotal', models.DecimalField(db_column='Subtotal', decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'item_orden',
                'managed': False,
            },
        ),
    ]
