# Generated by Django 5.1.7 on 2025-07-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_itemorden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemOrden',
        ),
    ]
