# Generated by Django 4.2.23 on 2025-08-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_productos_unidad_alter_productos_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='activo',
            field=models.BooleanField(db_column='Activo', default=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(db_column='Precio', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productos',
            name='unidad',
            field=models.CharField(db_column='Unidad', max_length=100),
        ),
    ]
