# Generated by Django 4.2.23 on 2025-08-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_productos_activo_alter_productos_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productos',
            name='unidad',
            field=models.CharField(max_length=100),
        ),
    ]
