# Generated by Django 4.2.23 on 2025-08-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_productos_activo_alter_productos_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
