# Generated by Django 4.2.23 on 2025-08-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_categoria_categoria_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='producto_id',
            field=models.PositiveIntegerField(db_column='Producto_ID', primary_key=True, serialize=False),
        ),
    ]
