# Generated by Django 4.2.23 on 2025-09-04 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_alter_productos_producto_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('horario_entrega', models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde')], max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.cliente')),
            ],
        ),
        migrations.RemoveField(
            model_name='orden',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='envio',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='productos',
        ),
        migrations.AlterUniqueTogether(
            name='ordendetalle',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ordendetalle',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='ordendetalle',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='OrdenDetalle',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.productos'),
        ),
    ]
