# Generated by Django 4.2.23 on 2025-09-04 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='envio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedidos.envio'),
        ),
    ]
