# Generated by Django 4.2.23 on 2025-09-04 04:27

from django.db import migrations, models
import datetime



class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_pedido_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_orden',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
