# Generated by Django 4.2.23 on 2025-09-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_pedido_fecha_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_orden',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
