# Generated by Django 4.2.23 on 2025-09-04 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_alter_pedido_fecha_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_orden',
        ),
    ]
