# Generated by Django 4.2.23 on 2025-09-04 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_remove_pedido_fecha_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_orden',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
