# Generated by Django 4.2.23 on 2025-09-04 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_remove_pedido_fecha_creacion_pedido_fecha_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_orden',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
