# Generated by Django 4.2.23 on 2025-09-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0019_alter_pedido_fecha_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_orden',
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
