# Generated by Django 4.2.23 on 2025-09-04 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0021_alter_pedido_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
