# Generated by Django 4.2.23 on 2025-09-04 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0023_alter_pedido_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha_creacion',
            new_name='fecha_orden',
        ),
    ]
