# Generated by Django 4.2.23 on 2025-09-04 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0024_rename_fecha_creacion_pedido_fecha_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.envio'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
