# Generated by Django 4.2.23 on 2025-09-04 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0025_alter_pedido_envio_alter_pedido_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='id',
            new_name='orden_id',
        ),
    ]
