# Generated by Django 4.2.23 on 2025-10-23 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0026_rename_id_pedido_orden_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='orden_id',
            new_name='pedido_id',
        ),
    ]
