# Generated by Django 4.2.23 on 2025-10-23 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0027_rename_orden_id_pedido_pedido_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='pedido_id',
            new_name='id',
        ),
    ]
