"""
Django settings for gestion_pedidos project.

Generated by 'django-admin startproject' using Django 4.2.2.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------
# Configuración de la base de datos
# ---------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ReyesCode$pancoquito',  # <- usa el nombre con prefijo
        'USER': 'ReyesCode',
        'PASSWORD': os.getenv('MYSQL_PASSWORD', ''),  # ponla como env var en PA
        'HOST': 'ReyesCode.mysql.pythonanywhere-services.com',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
        'CONN_MAX_AGE': 60,
    }
}

# ---------------------------
# Seguridad
# ---------------------------
# ⚠️ Usa variable de entorno en producción (ya no lo dejes hardcodeado)
SECRET_KEY = os.getenv('SECRET_KEY')  
if not SECRET_KEY:
    raise ValueError("No SECRET_KEY set in environment variables!")

 #'django-insecure-op33r&hz2e)*osaf5ggbye*dcxlovx6jpr8io+r1o=x_)(^mkm' 

DEBUG = True # True en desarrollo, False en producción

# Configuración para PythonAnywhere - REEMPLAZA 'tuusuario'
PYTHONANYWHERE_USER = 'ReyesCode'
PYTHONANYWHERE_DOMAIN = f'{PYTHONANYWHERE_USER}.pythonanywhere.com'

CSRF_TRUSTED_ORIGINS = [
    f'https://{PYTHONANYWHERE_DOMAIN}',
]

ALLOWED_HOSTS = [
    PYTHONANYWHERE_DOMAIN,
    'localhost',
    '127.0.0.1'
]

# ---------------------------
# Aplicaciones
# ---------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pedidos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = '/login/'

ROOT_URLCONF = 'gestion_pedidos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'pedidos', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestion_pedidos.wsgi.application'

# ---------------------------
# Validación de contraseñas
# ---------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ---------------------------
# Internacionalización
# ---------------------------
LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/Bogota'  # Ajustado a Colombia
USE_I18N = True
USE_TZ = True

# ---------------------------
# Archivos estáticos
# ---------------------------
STATIC_URL = '/static/'

# Aquí se recopilan los archivos cuando corres collectstatic
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Solo si tienes carpetas globales de estáticos fuera de las apps:
# STATICFILES_DIRS = [BASE_DIR / "assets"]

# ---------------------------
# Archivos media
# ---------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ---------------------------
# Otros ajustes
# ---------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_PROXY_SSL_HEADER = None
